### ISSUE TITLE
Years are comma'd

### ISSUE THREAD

**Issue by KevinMGranger** [KevinMGranger/comma-tater#1]
Perhaps I shouldn't comma-tate until the number is 5 digits long?

**Comment by rightpad** [comment]
Possibility: use regex to determine common date formats and ignore them. Eg: `xx/xx/NNNN` and `MONTH xx, NNNN` where `NNNN` is a four digit number you want to ignore.

**Comment by KevinMGranger** [comment]
I want to handle free-floating years too. People ought to be able to handle the lack of commas for 4-digit numbers.
